name: Go Coverage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.23']

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod tidy

      - name: Measure coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          verbose: true